version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/usr/src/app
      - bash_history:/bash_history
      - cargo_target:/cargo_target
    ports:
      - "5300:5300"
    working_dir: /usr/src/app
    restart: unless-stopped
    environment:
      CARGO_TARGET_DIR: /cargo_target/cache

  surrealdb:
    image: surrealdb/surrealdb:v1.2.1
    command: start -A --auth --user root --pass root --log=trace memory
    ports:
      - "8000:8000"
    volumes:
      - ./.mount/surrealdb:/data/database.db
    restart: unless-stopped

volumes:
  bash_history:
  # Used to speed up builds, because it uses a bind mount from the docker container
  # to the source files which are located in the OS. This results in slow compilation
  # and the build may fail periodically. With this solution we move the cargo build dir
  # to a docker volume which fixes these issues
  cargo_target:
